.github/workflows/html-proof.yaml, config.yaml, content/posts/category/sub-category/rich-content/index.bn.md, content/posts/category/sub-category/rich-content/index.md, content/posts/shortcodes/index.bn.md, content/posts/shortcodes/index.md, data/bn/sections/experiences.yaml, data/en/sections/experiences.yaml
=> Add HTML Proofer Action

config.yaml
=> Allow footer configuration

config.yaml, data/bn/site.yaml, data/en/site.yaml
=> Add disclaimer notice

config.yaml
=> Add mailchimp for newsletter

data/bn/sections/about.yaml, data/en/sections/about.yaml
=> Support certification badges in about section

data/bn/site.yaml, data/en/site.yaml
=> Add OpenGraph Headers

config.yaml
=> Documented matomo support config

.github/workflows/deploy-site.yaml, .github/workflows/lighthouse-check.yml, .github/workflows/md-link-check.yaml, .gitmodules, config.yaml, go.mod, go.sum, netlify.toml
=> Fix deploy preview + Use Hugo modules

config.yaml
Add on_card tags from feature https://github.com/hugo-toha/toha/pull/782
=> Add on_card tags from feature hugo-toha/toha#782

config.yaml
Adds reading time option, from the following feature
https://github.com/hugo-toha/toha/pull/784
=> Add reading time feature into config hugo-toha/toha#784

config.yaml
Add the feature hugo-toha/toha/pull/866 to config.yaml
Only merge after PR of hugo-toha/toha/pull/866 is accepted. (and when theme is updated)
=> Add max number of posts parameter

config.yaml
Adds the parameter `showAuthor`, for the recently added feature hugo-toha/toha/pull/870
=> Add showAuthor parameter

config.yaml, data/en/sections/accomplishments.yaml, data/en/sections/achievements.yaml, data/en/sections/featured-posts.yaml, data/en/sections/recent-posts.yaml
Add featured posts section hugo-toha/toha/pull/786.
=> Add featured posts section

config.yaml, data/en/sections/education.yaml
Adds education subsection, from the following feature: hugo-toha/toha/pull/888
=> Add education subsection

config.yaml, data/en/sections/education.yaml, data/en/sections/experiences.yaml
Adds `darkLogo` parameter for hugo-toha/toha/pull/903
=> Add dark logos

data/en/sections/education.yaml, data/en/sections/experiences.yaml
=> doc: fix darkLogo reference

netlify.toml
Update hugo, node and npm version to be aligned to theme repository
=> Update hugo, node and npm version

data/en/sections/skills.yaml
Reference PR: https://github.com/hugo-toha/toha/pull/979
=> Add category filter for skills

hugo.yaml
Provides the usage of the following features:
- https://github.com/hugo-toha/toha/pull/963
=> Add copy code button

hugo.yaml
Adds config for https://github.com/hugo-toha/toha/issues/1024
=> Add dark background
